version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_DB=fichtenfreund-local
      - POSTGRES_PASSWORD=abcfgh28374
    restart: unless-stopped
volumes:
  postgres-data:
